# Generated by Django 2.2.7 on 2019-11-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration',
        ),
    ]
